export const themeActionType = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
}

export const profileActionType = {
  UPDATE_PROFILE_DETAILS: 'UPDATE_PROFILE_DETAILS',
}

export const AdminActionType = {
  GET_STAFF_LIST: 'GET_STAFF_LIST',
  UPDATE_STAFF_LIST: 'UPDATE_STAFF_LIST',
  RESET_STAFF_LIST: 'RESET_STAFF_LIST',
  GET_STAFF_DETAILS: 'GET_STAFF_DETAILS',
  TOGGLE_STAFF_DETAILS: 'TOGGLE_STAFF_DETAILS',
  IS_FETCHING: 'IS_FETCHING',
  GET_STATISTICS: 'GET_STATISTICS',
  STATISTICS_IS_FETCHING: 'STATISTICS_IS_FETCHING',
}

export const StaffActionType = {
  GET_STAFF_APPLICATION_LIST: 'GET_STAFF_APPLICATION_LIST',
  GET_STAFF_APPLICATION_DETAIL: 'GET_STAFF_APPLICATION_DETAIL',
  GET_PC_APPLICATION_STATUS: 'GET_PC_APPLICATION_STATUS',
  GET_PC_APPLICATION_DETAIL: 'GET_PC_APPLICATION_DETAIL',
  GET_EG_APPLICATION_DETAIL: 'GET_EG_APPLICATION_DETAIL',
  //PG INTERNAL ACTION TYPES
  GET_PG_BMMU_STAFF_APPLICATION_LIST: 'GET_PG_BMMU_STAFF_APPLICATION_LIST',
}

export const loaders = {
  IS_CREATE_APP_FETCHING: 'IS_CREATE_APP_FETCHING',
  IS_CREATE_APP_GET_DRAFT_DETAILS_FETCHING:
    'IS_CREATE_APP_GET_DRAFT_DETAILS_FETCHING',
  IS_FETCHING_APPLICATION_LIST: 'IS_FETCHING_APPLICATION_LIST',
  IS_FETCHING_PROFILE_DETAILS: 'IS_FETCHING_PROFILE_DETAILS',
  IS_FETCHING_PC_APPLICATION_STATUS: 'IS_FETCHING_PC_APPLICATION_STATUS',
  IS_FETCHING_PC_APPLICATION_DETAIL: 'IS_FETCHING_PC_APPLICATION_DETAIL',
  IS_FETCHING_UPDATE_OPEN_APPLICATION: 'IS_FETCHING_UPDATE_OPEN_APPLICATION',
  IS_FETCHING_CHART_DATA: 'IS_FETCHING_CHART_DATA',
}

export const createApplication = {
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_1:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_1',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_2:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_2',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_3:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_3',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_4:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_4',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_5:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_5',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_6:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_6',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_7:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_7',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_8:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_8',
  UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_9:
    'UPDATE_PRODUCER_COLLECTIVE_FORM_STAGE_9',

  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_1: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_1',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_2: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_2',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_3: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_3',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_4: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_4',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_5: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_5',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_6: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_6',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_7: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_7',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_8: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_8',
  UPDATE_ENTERPRISE_GROUP_FORM_STAGE_9: 'UPDATE_ENTERPRISE_GROUP_FORM_STAGE_9',

  UPDATE_IA_FORM_STAGE_1: 'UPDATE_IA_FORM_STAGE_1',
  UPDATE_IA_FORM_STAGE_2: 'UPDATE_IA_FORM_STAGE_2',
  UPDATE_IA_FORM_STAGE_3: 'UPDATE_IA_FORM_STAGE_3',
  UPDATE_IA_FORM_STAGE_4: 'UPDATE_IA_FORM_STAGE_4',
  UPDATE_IA_FORM_STAGE_5: 'UPDATE_IA_FORM_STAGE_5',
  UPDATE_IA_FORM_STAGE_6: 'UPDATE_IA_FORM_STAGE_6',
  UPDATE_IA_FORM_STAGE_7: 'UPDATE_IA_FORM_STAGE_7',
  UPDATE_IA_FORM_STAGE_8: 'UPDATE_IA_FORM_STAGE_8',
  UPDATE_IA_FORM_STAGE_9: 'UPDATE_IA_FORM_STAGE_9',
  UPDATE_IA_FORM_STAGE_10: 'UPDATE_IA_FORM_STAGE_10',

  UPDATE_IE_FORM_STAGE_1: 'UPDATE_IE_FORM_STAGE_1',
  UPDATE_IE_FORM_STAGE_2: 'UPDATE_IE_FORM_STAGE_2',
  UPDATE_IE_FORM_STAGE_3: 'UPDATE_IE_FORM_STAGE_3',
  UPDATE_IE_FORM_STAGE_4: 'UPDATE_IE_FORM_STAGE_4',
  UPDATE_IE_FORM_STAGE_5: 'UPDATE_IE_FORM_STAGE_5',
  UPDATE_IE_FORM_STAGE_6: 'UPDATE_IE_FORM_STAGE_6',
  UPDATE_IE_FORM_STAGE_7: 'UPDATE_IE_FORM_STAGE_7',
  UPDATE_IE_FORM_STAGE_8: 'UPDATE_IE_FORM_STAGE_8',
  UPDATE_IE_FORM_STAGE_9: 'UPDATE_IE_FORM_STAGE_9',
  UPDATE_IE_FORM_STAGE_10: 'UPDATE_IE_FORM_STAGE_10',
}

export const createPgApplication = {
  UPDATE_PRODUCER_GROUP_FORM_STAGE_1: 'UPDATE_PRODUCER_GROUP_FORM_STAGE_1',
  UPDATE_PRODUCER_GROUP_FORM_STAGE_2: 'UPDATE_PRODUCER_GROUP_FORM_STAGE_2',
  UPDATE_PRODUCER_GROUP_FORM_STAGE_3: 'UPDATE_PRODUCER_GROUP_FORM_STAGE_3',
  UPDATE_PRODUCER_GROUP_FORM_STAGE_4: 'UPDATE_PRODUCER_GROUP_FORM_STAGE_4',
  UPDATE_PRODUCER_GROUP_FORM_STAGE_5: 'UPDATE_PRODUCER_GROUP_FORM_STAGE_5',
  UPDATE_PRODUCER_GROUP_FORM_STAGE_6: 'UPDATE_PRODUCER_GROUP_FORM_STAGE_6',
  UPDATE_PRODUCER_GROUP_FORM_STAGE_7: 'UPDATE_PRODUCER_GROUP_FORM_STAGE_7',
  RESET: 'RESET',
}

export const common = {
  RESET: 'RESET',
  APPLICATION_FORM_RESET: 'APPLICATION_FORM_RESET',
  UPDATE_APPLICATION_STAGES: 'UPDATE_APPLICATION_STAGES',
  UPDATE_SYMR_MASTER_DATA: 'UPDATE_SYMR_MASTER_DATA',
  UPDATE_IA_MASTER_DATA: 'UPDATE_IA_MASTER_DATA',
  UPDATE_IE_MASTER_DATA: 'UPDATE_IE_MASTER_DATA',
  UPDATE_PC_MASTER_DATA: 'UPDATE_PC_MASTER_DATA',
  RESET_APPLICATION_DETAIL: 'RESET_APPLICATION_DETAIL',
  RESET_STAFF_DETAILS: 'RESET_STAFF_DETAILS',
}

export const SYMRFORM = {
  UPDATE_SYMR_FORM_STAGE_1: 'UPDATE_SYMR_FORM_STAGE_1',
  UPDATE_SYMR_FORM_STAGE_2: 'UPDATE_SYMR_FORM_STAGE_2',
  UPDATE_SYMR_FORM_STAGE_3: 'UPDATE_SYMR_FORM_STAGE_3',
  UPDATE_SYMR_FORM_STAGE_4: 'UPDATE_SYMR_FORM_STAGE_4',
  UPDATE_SYMR_FORM_STAGE_5: 'UPDATE_SYMR_FORM_STAGE_5',
  UPDATE_SYMR_FORM_STAGE_6: 'UPDATE_SYMR_FORM_STAGE_6',
  UPDATE_SYMR_FORM_STAGE_7: 'UPDATE_SYMR_FORM_STAGE_7',
  UPDATE_SYMR_FORM_STAGE_8: 'UPDATE_SYMR_FORM_STAGE_8',
}

export const getFundChart = {
  UPDATE_FUND_CHART_TAB_1: 'UPDATE_FUND_CHART_TAB_1',
  UPDATE_FUND_CHART_TAB_2: 'UPDATE_FUND_CHART_TAB_2',
}

export const getEnterpiseChart = {
  UPDATE_ENTERPRISE_CHART_TAB_1: 'UPDATE_ENTERPRISE_CHART_TAB_1',
  UPDATE_ENTERPRISE_CHART_TAB_2: 'UPDATE_ENTERPRISE_CHART_TAB_2',
  UPDATE_ENTERPRISE_CHART_TAB_3: 'UPDATE_ENTERPRISE_CHART_TAB_3',
  UPDATE_ENTERPRISE_CHART_TAB_4: 'UPDATE_ENTERPRISE_CHART_TAB_4',
  UPDATE_ENTERPRISE_CHART_TAB_5: 'UPDATE_ENTERPRISE_CHART_TAB_5',
}

export const getBeneficiaryCharts = {
  UPDATE_BENIFICIARY_CHART_TAB_1: 'UPDATE_BENIFICIARY_CHART_TAB_1',
  UPDATE_BENIFICIARY_CHART_TAB_2: 'UPDATE_BENIFICIARY_CHART_TAB_2',
  UPDATE_BENIFICIARY_CHART_TAB_3: 'UPDATE_BENIFICIARY_CHART_TAB_3',
  UPDATE_BENIFICIARY_CHART_TAB_4: 'UPDATE_BENIFICIARY_CHART_TAB_4',
  UPDATE_BENIFICIARY_CHART_TAB_5: 'UPDATE_BENIFICIARY_CHART_TAB_5',
  UPDATE_BENIFICIARY_CHART_TAB_6: 'UPDATE_BENIFICIARY_CHART_TAB_6',
}

export const getApplicationCharts = {
  UPDATE_APPLICATION_CHART_TAB_1: 'UPDATE_APPLICATION_CHART_TAB_1',
  UPDATE_APPLICATION_CHART_TAB_2: 'UPDATE_APPLICATION_CHART_TAB_2',
}
