export {
    Login,
    Register,
    ValidateOTP,
    SetPassword,
    ForgotPassword,
    ChangePassword,
    StaffLogin,
    StaffRegister,
    StaffPasswordReset,
    StaffForgotPassword,
    StaffSentResetPassword,
    StaffForgotUserId,
    StaffVerifyDetails,
    StaffResetPasswordMessage
} from "./onBoarding";
export {
    UserDashboard,
    ProductiveCollectiveForm,
    ProductiveCollectiveReview,
    ProducerGroupForm,
    ProducerGroupReview,
    EnterpriseGroupForm,
    EnterpriseGroupReview,
    View,
    PgView,
    Assessment,
    PcServiceAndBlockMembers,
    ProjectCoverageAndMembers,
    StaffDashboard,
    ProducerCollectiveApplication,
    ProducerGroupApplication,
    UserManagement,
    FirstLevelAssessment,
    CreateUser,
    SYMRProductiveCollectiveForm,
    SYMRProductiveCollectiveReview,
    SYMRView,
    //INTERNAL
    SYMRApplication,
    EnterpriseGroupApplication,
    IndividualEnterpriseApplication,
    egView,
    Funds,
    Enterprises,
    IndividualEnterpriseForm,
    IndividualEnterpriseReview,
    ieView,
    DiffabledVulnerableForm,
    DiffabledVulnerableReview,
    diffabledView,
    Home,
    Reports,
    UnderConstruction,
    Applications
} from "./dashboard";

export { Beneficiaries } from "./dashboard/Staff/index"